### ISSUE TITLE
Add Launchpad to Sloth Finance

### ISSUE THREAD

**Issue by yuriy77k** [Fushuma/Dev_grants#4] opened 2024-03-14 17:40 UTC
# Development Grant: Launchpad for Sloth Finance

## Technical Details:

Launchpad should be like this: https://www.pinksale.finance/launchpads?chain=BSC but with Sloth Finance graphics style.

Information for each launchpad card should be taken from JSON in a config file.
For example:
```js
const launchpads = {
  card1: {
    name: "Project name",
    symbol: "Token symbol",
    address: "Token contract address",
    logo: "link to the logo",
    description: "Project description",
    startDate: "timestamp when the sale ends",
    endDate: "timestamp when the sale ends",
    icoContract: "Address of ICO contract",
    ...
  },
  card2: {

  },
  ...
} 
```

Information about ICO progress should be read from ICO smart contract.

- **Technology stack:** Javascript, React
- **Current state:** https://app.soy.finance/
- Source code of Sloth Finance UI: https://github.com/CallistoEnterprise/soy-finance-app-v2

**Comment by ERROR-SYS** [comment] 2024-03-14 18:06
I am not sure if I will do it or no but can I have more informations about the location of the JSON data? Should I place it in src/config/launchpad/launchpads.ts ??

**Comment by ERROR-SYS** [comment] 2024-03-15 01:50
I am making the UI and I would like to know more about the way the data will be insered to the JSON file.

**Comment by yuriy77k** [comment] 2024-03-15 13:14
> I am not sure if I will do it or no but can I have more informations about the location of the JSON data? Should I place it in src/config/launchpad/launchpads.ts ??

yes, it can be there

**Comment by yuriy77k** [comment] 2024-03-15 13:17
> I am making the UI and I would like to know more about the way the data will be insered to the JSON file.

For begin, data can be inserted manually,

But later, will be good to have a page "Create launchpad"  where a project provides all required information and it should be added to the list of launchpads. But in this case, we can't use a config file, right?

**Comment by ERROR-SYS** [comment] 2024-03-15 13:49
> For begin, data can be inserted manually,


Okay!

> we can't use a config file, right?


No, I think we can do a system that works with smart contracts. Like you said have a page to create launchpad, provide all the infos of the ICO and have a create button that will create a launchpad in smart contract. The data will be fetched from that smart contract, maybe it will work like this?

**Comment by yuriy77k** [comment] 2024-03-15 16:21
> No, I think we can do a system that works with smart contracts. Like you said have a page to create launchpad, provide all the infos of the ICO and have a create button that will create a launchpad in smart contract. The data will be fetched from that smart contract, maybe it will work like this?

We can't store all the info in a smart contract, it will be very expensive in gas. The better solution is to use a backend with a database to store the required info. But for now, we can work with manually editing the config.

**Comment by Dalcor** [comment] 2024-03-15 18:42
I could provide that functionality for you. I'm familiar with tech. stack used in current exchange version (including next.js, viem/wagmi and tailwind)

Update will include:
- Launchpad mockups
- Launchpad page on sloth.finance with cards. Each card will have button that will open the dialog with short info about the project and form to buy tokens with it.
- Smart contract integration
- Updating menu to include Launchpads page
- Mobile version adaptation
- Dark/Light theme support
- Text for new pages will be covered with translation variables and translated to UA lang.
- ICO Purchase operations will be integrated in our recent transactions module. You will see pending transactions and could track its status.
-* I will provide strict formatting rules for project, so everybody who is working on with project will use same code style
-* I've detected issue with multiple injected wallets connection. The thing is, coinbase, trust and metamask all uses same object for connection. So if now you will enable trust wallet and metamask and try to connect to metamask it will open TrustWallet app. I've already figured out how to fix that, and I will add this fix to update as well. Also I could add coinbase wallet connection if needed (I think for ICOs it is great to cover as much wallets as we can)

The update will cost $1200 and will take about 7-10 days.

**Comment by ERROR-SYS** [comment] 2024-03-16 14:15
Hey, here's a small update 

I followed the instructions of Yuriy but adapted it to Sloth Finance style.

+ Launchpad list page is completed (screenshots)

+ Project info page under progress (completion 60%)
 
I think I can complete it for Wednesday (including responsive), I could need some help for smart contract integration.

Cost: $800.

![image](https://github.com/Fushuma/Dev_grants/assets/62564023/c08726f4-82d3-4b03-ace8-b65b5b5f337a)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/7406c8b7-bd5d-45df-b9e5-b634737d1cd5)

**Comment by creepas** [comment] 2024-03-16 19:57
Oh this seems really good mate.

I will talk on monday with the team. You have it on github so we can take a
look on the code and possibly start integrating smart contracts?

cReepas

**Comment by ERROR-SYS** [comment] 2024-03-17 02:00
Sounds good. I will share the repo's link by Monday.

Today, I improved the code of the Launchpad list page, and from my point of view it is completed. (screenshot 1)

I also made some progress in the code of the Project info page, so tomorrow I will work on smart contracts integration, if I have questions I will ask them here. (screenshot 2)

I dont think that its crucial but I want to mention that Sloth Finance's UI depends on the Tailwind library, I dont know it very well, so I used it when I could but wrote the majority of styles with CSS. However I plan to continue to work on Tailwind so I will be able to rewrite it in a few weeks, I hope its fine.

![image](https://github.com/Fushuma/Dev_grants/assets/62564023/0f764f75-7f41-46b5-86be-ef70810270f6)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/489c7dfb-998f-4109-829c-44fbc02036d4)

**Comment by yuriy77k** [comment] 2024-03-17 09:23
@ErrSystem you should not spend much time on it until we approve your offer. We'll discuss the proposed offers on Monday and write here what we choose.

**Comment by ERROR-SYS** [comment] 2024-03-17 23:14
Hey @yuriy77k , actually I started to work on it 3 days ago and have completed the code. I wanted to work on the smart contract integration today but I will wait for you.

I have invited you and creepas to the repo so you can get the code, and a demo of the Launchpad page is online: https://streamable.com/ze06n8

- Demo note: At 0:50: 100,000 Solana tokens have been sold. (see point 5 of Project info page)

Here are some of the features implemented:

1. Design inspired from Sloth Finance
2. Light and dark modes supported
3. The pages are responsive
4. Various animations and user friendly optimisation

Launchpads list page:

1. Cards are updated automaticaly according to a config file
2. Media section and Soft / Hard cap are optional if empty these parameters will not be shown
3. The cards are sorted by state, live sales first, then the sales to come, then ended sales
4. A card is deleted automaticaly 60d after completion (can be edited or removed)
5. A card's state (live/soon/ended) is updated automaticaly
6. When the sale ends, the timer is replaced by the end date

Project info page:

1. If selected network is not the ICO's network the Buy button will be replaced by switch {network name}
2. If wallet is disonnected, the Buy button will be replaced by connect wallet
3. If entry is 0 then the buy button is disabled
4. 1 coin is deducted from the input provided by the max button (Gas fee)
5. UI don't allow the user to buy more than the tokens available on the contract (calculed like this: token for sale - current supply), if you do so the input value will automaticaly turn into the available tokens.
6. Added a button to add the token to metamask

**Comment by yuriy77k** [comment] 2024-03-21 12:34
@ErrSystem your offer is approved.

You should Implement:

1. Smart Contract integration to display ICO information from the contract (function `getCurrentRound()`) and buy tokens (function `buyToken()`).
- https://github.com/CallistoEnterprise/LiveDiff/tree/main?tab=readme-ov-file#ico-contract-functions-to-use-in-ui
- ICO contract ABI you can take from here: https://explorer.callisto.network/address/0x9953475C1bA240757c1b2731586C6d3C774b5167/contracts

2. Launchpad should support many chains and many tokens. 

For example in JSON config should be such parameters:
```js
const launchpads = {
card1: {
    ...
    chains: {
        "820": [
            "busdt", "bnb", // tokens from chain's token list, for example: \src\config\token-lists\tokenListInCLO.ts
            "native" // native coin, in chain 820 it's CLO
        ],
        "61": ["native"], // ETC
        ...
    }
    ...
  },
  card2: {

  },
  ...
}
```
Depending on the current chain, a user should be able to choose which token he wants to pay.
![tokenList](https://github.com/Fushuma/Dev_grants/assets/39490997/9a372026-5f43-44c4-bae6-4ddfbf1cd6a6)

3. If a card has the parameter:  `"vestingContract": "0xe5A5837b96176d6E47E541F186B2348DED2c0A1d"` we should display vesting details like [here](https://app.soy.finance/uk/migrate):
![vesting](https://github.com/Fushuma/Dev_grants/assets/39490997/89d4b51b-8f51-4ce4-a452-59a4d28d3821)

Use the function `getUnlockedAmount` to get vesting info and the function `claim` for claiming unlocked tokens.
- https://github.com/CallistoEnterprise/LiveDiff/tree/main?tab=readme-ov-file#view-function-getunlockedamount
- Vesting  contract ABI you can take from here: https://explorer.callisto.network/address/0xe5A5837b96176d6E47E541F186B2348DED2c0A1d/read-contract

**Comment by ERROR-SYS** [comment] 2024-03-23 18:32
Okay, I will start working on it.

**Comment by ERROR-SYS** [comment] 2024-03-24 23:10
Hello @yuriy77k, I started to work on the smart contracts integration today. For testing purpose, I tried to get the informations from the ICO of LiveDiff but I figured out that the values returned are not as defined in the [linked documentation](https://github.com/CallistoEnterprise/LiveDiff/tree/main?tab=readme-ov-file#ico-contract-functions-to-use-in-ui). 
- When I call `getCurrentRound()`, the output is:

`{ amount: 0n,
price: 0n,
roundStarts: 0n,
totalReceived: 0n,
totalSold: 0n }`

The contract doesnt return the 'endDate' and 'startDate' parameters.
Any thoughs?

**Comment by yuriy77k** [comment] 2024-03-25 15:34
@ErrSystem sorry, the ICO contract was updated, but the documentation wasn't. Now I updated it.

**Comment by ERROR-SYS** [comment] 2024-03-25 17:00
Thank you for your answer. 

What about the endDate value? How I can get it?

**Comment by yuriy77k** [comment] 2024-03-25 20:22
> What about the endDate value? How I can get it?

In this ICO there is no endDate in the contract (the new round starts when all tokens from the previous will be sold).

So use endDate from the config parameter.

**Comment by ErrSystem** [comment] 2024-03-31 22:22
Hey, I just wanted to tell you that I am still working on the launchpad upgrades and that I've done a lot of changes, It took me more time because of some personal things. I also made sure to use some systems that have been implemented before to make it like it has been developped by the same team members.

**Comment by ERROR-SYS** [comment] 2024-04-01 01:06
Hey, I just wanted to tell you that I am still working on the launchpad upgrades and that I've done a lot of changes, It took me more time because I was busy with some personal things. I ensured to incorporate pre-existing systems to enhance the integration of the launchpads in the app.

Here are some changes I have done:
- Fetch token data from the token address directly.
- Fetch ICO data from the ICO contract directly.
- Added multiChain for ICOs (one ICO can have multiple chains).
- Added a menu to select chains for launchpads due to the dynamic smart contract requests (can't request smart contracts to get the data if you are not connected to the correct chain) the chains in this menu are updated automatically using some already existing config files (every time you add a chain to sloth finance it will update the list of chains automatically).
- You can directly see in the select chains menu how many launchpads are active in that chain.
- Selecting a chain while being disconnected from the wallet provider will make the UI show you the connect menu with the selected chain already chosen for you.
- Selecting a chain while being connected to another chain will make the UI request a chain switch to that chain.
- Chains appear based on the active launchpads count (bigger count shows first then the second then...).
- Infos for cards (token infos and ICO infos) are taken directly from contracts available on your chain (if it's supported by the ICO) instead of the first defined chain in the config file.
- Updated timers text and removed seconds, if days = 0 it will only show hours and minutes and if days and hours = 0 it will only show minutes.
- ICOs are now classed as “Ended” when they are completed.
- Added ICO’s chain logo in the right bottom of the project’s logo.
- If the ICO is available on 2 chains both will be shown, if it supports more then the logos will be replaced by a “+” sign (you can provide a better picture if you want).
- Added vesting section that appears only if it's supported by the ICO.
- You can now pay with multiple tokens (defined in the config file and importing them from already defined files).
- Replaced token symbols in inputs by their logo.
- Added dropdown in the first input to select coin/tokens (infinite capacity depending on the defined tokens in the config file).
- Added a warning when the user enters an amount of tokens that exceed the available tokens on contract.
- When switching the chain / coin / token, the prices / currencies automatically change without any refresh.
- You can't select a coin / token if you are not connected or if you are connected on a wrong chain.
- Due to gas fees costs, the UI detects if the token is native or not and decides if it needs to reduce the max button output by 0.05%.
- Added a section to switch to supported chains in the project’s description.
- When you switch chains (from supported to unsupported) the values from smart contracts are not forgotten (the UI shows the last informations received from the smart contracts and doesnt return 'undefined' ).
- Claim vesting rewards uses the recent transaction system to track it in the app directly.
- If the user changes his chain while being in the details page, and clicks on 'get back' button, the UI will send him back to the chain selector while informing him using a toast (added this to avoid unexpected errors and wrong data).
- Added the switch network animations and some toasts (warnings/alerts) when needed.
- Added error handling while loading cards.
- Added a better loading system.

**Comment by ERROR-SYS** [comment] 2024-04-07 03:24
Hello, I have almost finished the page., the only thing left is the functionality to buy the tokens. Here are some changes I have made this week:

- Added animations for the select chain section.
- Fixed a bug with the progress bar that showed NaN if the currentSupply or the amount to sell was 0.
- Now, each currency has its own price in the config file.
- You can ignore payments using native coins in the config file (useNativeAsPayment) and only accept defined tokens.
- When switching the chain/coin/token the prices/currencies automatically update without refresh.
- You can't select a coin/token if you are not connected on the right hain.
- Everytime you switch to a supported network the "Amount to pay" input value resets to 1.
- Fixed a bug where the selectors buttons didn’t work properly when the user’s balance is zero.
- Balance fetch function now switches automatically to the selected token.
- Balance now refetch automatically before each operation that involves processing its data.
- Explorer links is updated based on the current chain.
- Replaced the currencies of soft/hard cap with USD (due to multi-token and multi-chain systems).
- Corrected name parameter values in the nativeTokens file (before it was its symbol).
- Added and edited some styles.

I updated the readme file in the page repo with the variables required to add a chain to Sloth Finance. I made them minimal so every dev can do it.

Here are some screenshots of the different sections of the page (note that some values are missing because there is no smart contract to take informations from):

![image](https://github.com/Fushuma/Dev_grants/assets/62564023/a9236a87-ea20-4d14-aca6-d467bc8beca0)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/c172097c-46fa-4100-8a93-e7a6c9707cc4)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/d595d6ab-b97e-4da1-ab79-9fcf6fc9753e)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/ddcb595d-39c2-4f74-961b-70bad4e67448)

_Note: the "+" image in the second picture means that the ICO supports more than 2 chains._

## Questions & Testing:

1. For testing prurposes, I would like to have an ICO contract on 2 chains and have the possibility of editing its totalSold, do you think it is possible?

2. The ICOs are organized by status "Live", "Soon", "Ended", which means that when an ICO is completed, it is automatically marked as "Ended". However, if an ICO is sold out then the end date from the config file will be wrong, we therefore need to fetch this data from the smart contract. Can you add it?

**Comment by ERROR-SYS** [comment] 2024-04-11 20:00
Hello @yuriy77k any update on my questions?

On my side, I added the function to buy ICO tokens. However, I think that a more suitable approach for the launchpads page is to have one function to buy with the coin and one to buy with tokens (while precising in the arguments the token address), can you do this?

I also updated the repo if you want to check the code.

**Comment by spatialiste** [comment] 2024-05-01 10:55
Hello @ErrSystem, sorry for the late answer; we have several things ongoing, so... However, this morning we discussed with @yuriy77k and this is what comes out:

**_1. For testing prurposes, I would like to have an ICO contract on 2 chains and have the possibility of editing its totalSold, do you think it is possible?_**

**_2. The ICOs are organized by status "Live", "Soon", "Ended", which means that when an ICO is completed, it is automatically marked as "Ended". However, if an ICO is sold out then the end date from the config file will be wrong, we therefore need to fetch this data from the smart contract. Can you add it?_**

We don't really want to edit the smart contract for now, so let's do the tests on Callisto Network, without the end date, please simply mark the sale as "Ended" when it's over.

But this is a great feature, and we could implement it in an upgrade.
 
_**3. A more suitable approach for the launchpads page is to have one function to buy with the coin and one to buy with tokens (while precising in the arguments the token address), can you do this?**_

Yes, the function to buy with coins is planned and will be added later. For now, let's start testing the UI with the LiveDIFF token. Please create a config file with the info below, and create a pull request into the `development` branch of this repo: https://github.com/CallistoEnterprise/soy-finance-app-v2:

- LiveDIFF token
    0xdf4Da43DD3E9918F0784f8c92b8aa1b304C43243
- ICO contract
    0xcDCf1A978553f64AC55F280702D2Cdd239a49beA
- Vesting contract
    0xe5A5837b96176d6E47E541F186B2348DED2c0A1d
- BUSDT token 
    0xbf6c50889d3a620eb42C0F188b65aDe90De958c4

Thank you.

**Comment by ERROR-SYS** [comment] 2024-05-11 01:02
Hey @spatialiste, @yuriy77k, I've made a pull request to the `developement` branch as you requested.

**Sloth Finance Patch notes:**
- Since, I started working on the launchpads before the last migration update (CE2, CE3...) I implemented the latest updates in my repository.
- Added LiveDiff launchpad for testing.
- Removed the end date & time when the sale is finished.
- You can now type decimals in the input.
- Edited some text.
- Replaced dots with commas in large numbers.
- Fixed all the bugs I encountred while testing.
- Responsive improvements.

_Note: the structure of some files might have changed because of the extension `Prettier` but the functionalities are not impacted._

[Sloth Finance: Launchpads, Pull request.](https://github.com/CallistoEnterprise/soy-finance-app-v2/pull/11)
[Sloth Finance: Launchpads, Deployed website.](https://deploy-preview-11--app-sloth-finance.netlify.app/)

The LiveDiff test launchpad will end the 17/05/2024 12:00 UTC.

**Comment by spatialiste** [comment] 2024-05-15 08:12
Hello @ErrSystem. We are starting to review the page today and we will get back to you by Friday.
Thanks a lot.

**Comment by spatialiste** [comment] 2024-05-16 10:07
Hi @ErrSystem, we've done some testing and the UI is great, but we found an issue, when attempting to purchase from Trust Wallet without BUSDT, the network is set to Ethereum instead of Callisto Network. This problem does not occur with Metamask.

Could you please check?

https://github.com/Fushuma/Dev_grants/assets/41175366/a6cf1364-a3bb-4ea7-ba27-7c332538490a

**Comment by ERROR-SYS** [comment] 2024-05-20 00:17
Hey @spatialiste, I've run some tests and didn't encounter the error. However I've published a new version of the page where transactions can't be sent unless you have the required amount of tokens, which should resolve the issue.

_Updated end date of the LiveDiff launchpad: 22/05/2024 18:00 UTC._

**Comment by spatialiste** [comment] 2024-05-21 11:37
> Hey @spatialiste, I've run some tests and didn't encounter the error. However I've published a new version of the page where transactions can't be sent unless you have the required amount of tokens, which should resolve the issue.
> 
> _Updated end date of the LiveDiff launchpad: 22/05/2024 18:00 UTC._

Hello, so we made some more tests, and it works great; just that when the decimal is too long, the transaction is rejected, so please reduce it to 3 or 4 numbers. I would also prefer to have the "Details" button in green so that it will be more visible.

Last point: Could you please disable the menu entries "Boost Token" and "Burn & Boost" so that we can allocate the rocket icon to the launchpad?

**Comment by ERROR-SYS** [comment] 2024-05-28 01:20
Hello @spatialiste, I've made the menu changes and switched the details button background to green as per your request. Additionally, I've fixed the bug you mentioned and addressed a few other issues as well.

_Updated end date of the LiveDiff launchpad: 30/05/2024 18:00 UTC._

**Comment by spatialiste** [comment] 2024-05-28 10:41
> Hello @spatialiste, I've made the menu changes and switched the details button background to green as per your request. Additionally, I've fixed the bug you mentioned and addressed a few other issues as well.
> 
> _Updated end date of the LiveDiff launchpad: 30/05/2024 18:00 UTC._

Hello @ErrSystem, We made some tests and found an error that was not present in the previous version. When setting the transaction value to "Max," the value is too big, and an error occurs (see screenshot).

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/c0c66640-2726-4ec9-9989-87aa0690abcb)

Finally a last request, could we set "Return" as a button like we did for "Details"?

![image](https://github.com/Fushuma/Dev_grants/assets/41175366/5d8a43f6-8a88-4326-ad7a-273858f4c403)

**Comment by ERROR-SYS** [comment] 2024-05-28 16:50
Hello, I've made the changes you requested on the "Return" and "Go Back!" buttons:

![image](https://github.com/Fushuma/Dev_grants/assets/62564023/72cb168b-83d6-4b67-8e74-eff76aede286)
![image](https://github.com/Fushuma/Dev_grants/assets/62564023/1d33c979-3a21-486b-9397-6646408e6484)

The issue you mentioned was caused by the decimal changes I've made in the previous version and its now resolved. I also fixed some other visual bugs.

**Comment by ERROR-SYS** [comment] 2024-05-28 20:44
Hey, I checked again and updated the code to fix some input issues. You can check the commit [here](https://github.com/CallistoEnterprise/soy-finance-app-v2/pull/11/commits/ffa2bc1395a9105468369182465e85134d6ac008).

**Comment by spatialiste** [comment] 2024-05-29 11:57
> Hey, I checked again and updated the code to fix some input issues. You can check the commit [here](https://github.com/CallistoEnterprise/soy-finance-app-v2/pull/11/commits/ffa2bc1395a9105468369182465e85134d6ac008).

Thank you. We tested it this morning, and it works great. We will proceed with the payment to your wallet this afternoon.

**Edit: Please provide me with a wallet address for the payment.**

Thanks again.

**Comment by ERROR-SYS** [comment] 2024-05-29 18:32
Hey @spatialiste, I am happy to hear that, here is my wallet address: 0x28544a8e2cdd21f58479628caf41da3b1884acb9

**Comment by spatialiste** [comment] 2024-05-30 13:21
Hello @ErrSystem, We just processed the payment. Thank you again for participating in this grant and for the work you accomplished. 

**This grant is now completed.**

Tx Link: https://bscscan.com/tx/0x93bb069d81d03a14522201ea88e0a06766efd3334533871b890425e07b0003e4

**Closed as completed** 2024-05-30 13:34 UTC
